name: ebuoy
description: The English Buoy.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.16+1.2.16

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_widgets: ^0.1.6 # 其中有能按 index scroll 的 list view
  flutter_slidable: ^0.5.3 # 列表 item 滑动删除
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1 # 打开url链接
  #cupertino_icons: ^0.1.2
  dio: ^3.0.7 # http 请求
  easy_alert: ^0.0.2
  #google_sign_in: ^4.1.1 # google 登录
  #drowngrading to 4.0.7 try avoid crash on iOS
  google_sign_in: ^4.0.7 # google 登录
  shared_preferences: ^0.5.6 # 数据持久化存储
  provider: ^4.0.1 # 状态管理器

  flutter_spinkit: "^4.0.0" # loading 动画
  receive_sharing_intent: ^1.3.2 # 接收分享过来的内容
  modal_progress_hud: ^0.1.3 # loading 遮盖
  cached_network_image: 2.0.0-rc.1 # 缓存网络图片
  rflutter_alert: ^1.0.3 # alert
  flutter_picker: ^1.1.0 # 选择数字
  youtube_player_flutter:
    git:
      url: https://github.com/bigzhu/youtube_player_flutter
  # youtube_player_flutter: ^6.0.3+2
  #flutter_youtube_view: ^1.1.7








  #share:
  #  git:
  #    url: https://github.com/d-silveira/flutter-share.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the

# The following section is specdevc to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in

  assets:
    - assets/images/
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
